image: docker-registry.i.brainpp.cn/brain/ci-base:18.04

style:
    script:
        - python3 -V
        - export PATH=/root/.local/bin:$PATH
        - pip3 install -r requirements.txt -r requirements.dev.txt --user
        - make style-check
    tags:
        - emtf

unittest:
    script:
        - export PATH=/root/.local/bin:$PATH
        - pip3 install -r requirements.txt -r requirements.dev.txt --user
        - make test
    artifacts:
        paths:
            - htmlcov
    tags:
        - emtf

pages:
    stage: deploy
    dependencies:
        - unittest
    script:
        - mkdir public
        - mv htmlcov public/cov
    artifacts:
        paths:
            - public
    only:
        - master
        - dev
    tags:
        - emtf

release:
    stage: deploy
    dependencies:
        - unittest
    script:
        - export PATH=/root/.local/bin:$PATH
        - pip3 install -r requirements.txt -r requirements.dev.txt --user
        - make test
        - make wheel
        - devpi use "${DEVPI_URL}"
        - devpi login "${DEVPI_LOGIN}" --password="${DEVPI_PASSWORD}" && devpi upload dist/*
    only:
        - tags
    tags:
        - emtf
