repos:
-   repo: git@git-core.megvii-inc.com:zxy/black.git
    rev: 19.3b0
    hooks:
    -   id: black
        language_version: python3.6
-   repo: git@git-core.megvii-inc.com:zxy/pre-commit-hooks.git
    rev: v2.3.0
    hooks:
    -   id: flake8
        args: ["--ignore=E501,E203,F401,W503,W504"]
    -   id: requirements-txt-fixer
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: check-docstring-first
    -   id: check-executables-have-shebangs
    -   id: check-merge-conflict
    -   id: debug-statements
-   repo: git@git-core.megvii-inc.com:zxy/mirrors-mypy.git
    rev: v0.720
    hooks:
    -   id: mypy
        args: ['--ignore-missing-imports']
